# Generated by Django 5.1.1 on 2024-09-06 14:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=16, null=True)),
                ('country_code', models.CharField(default='+91', max_length=5)),
                ('address', models.TextField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(auto_now=True)),
                ('user_invalid_attempt', models.IntegerField(default=0)),
                ('user_invalid_attempt_at', models.DateTimeField(null=True)),
                ('user_timezone', models.CharField(blank=True, default='Asia/Kolkata', max_length=250, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppleHealthStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateTimeField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bodyMass', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bodyFatPercentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('biologicalSex', models.CharField(blank=True, max_length=32, null=True)),
                ('activityMoveMode', models.CharField(blank=True, max_length=128, null=True)),
                ('stepCount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('basalEnergyBurned', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activeEnergyBurned', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flightsClimbed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('appleExerciseTime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('appleMoveTime', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('appleStandHour', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('menstrualFlow', models.CharField(blank=True, max_length=128, null=True)),
                ('HKWorkoutTypeIdentifier', models.CharField(blank=True, max_length=128, null=True)),
                ('heartRate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygenSaturation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mindfulSession', models.JSONField(blank=True, null=True)),
                ('sleepAnalysis', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apple_health_stat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
